version: "2"
plugins: 
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      extensions:
        - .js
        - .jsx
      config:
        - .eslintrc.json
exclude_patterns:
  - "dist/**"
  - "dist-stage/**"
  - "node_modules/**"
  - "**/__mocks__/**"
  - "**/__tests__/**"
  - "cypress/**"
checks:
  identical-code:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 100